#!/bin/bash
# Simple script to display setup instructions from CachyOS live environment

echo "========================================="
echo "CachyOS Setup Instructions"
echo "========================================="
echo ""
echo "Your CachyOS USB stick is ready!"
echo ""
echo "To set up your system with R9700 inference capabilities:"
echo ""
echo "1. Install CachyOS using the graphical installer"
echo "2. After installation and reboot, download the bootstrap scripts:"
echo ""
echo "   git clone https://github.com/yourusername/cachyos-setup.git ~/cachyos-setup"
echo "   cd ~/cachyos-setup"
echo "   chmod +x *.sh"
echo "   ./bootstrap.sh"
echo ""
echo "3. The bootstrap will:"
echo "   - Configure ASRock Creator Radeon AI PRO R9700 for AI/ML inference"
echo "   - Set up development environment with Docker, Python, Rust, etc."
echo "   - Configure shell, security, and system optimization"
echo ""
echo "Note: You need to upload the bootstrap scripts to GitHub first."
echo "The scripts are currently in: /home/spag/cachyos_setup/"
echo ""
echo "To upload to GitHub:"
echo "1. Create a new repository: cachyos-setup"
echo "2. Push the scripts:"
echo "   cd /home/spag/cachyos_setup"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Add CachyOS bootstrap scripts'"
echo "   git remote add origin https://github.com/yourusername/cachyos-setup.git"
echo "   git push -u origin main"
echo ""
echo "========================================="